"""create_user_course_enrollments

Revision ID: 82d18f7218de
Revises: e80d87fd4f52
Create Date: 2026-02-15 20:29:27.883858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d18f7218de'
down_revision: Union[str, Sequence[str], None] = 'e80d87fd4f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_course_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否为当前正在学习的课程'),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_user_course_enrollment')
    )
    op.create_index(op.f('ix_user_course_enrollments_id'), 'user_course_enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_user_course_enrollments_user_id'), 'user_course_enrollments', ['user_id'], unique=False)
    op.create_index(op.f('ix_practice_submissions_id'), 'practice_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_practice_submissions_lesson_id'), 'practice_submissions', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_practice_submissions_user_id'), 'practice_submissions', ['user_id'], unique=False)
    op.create_index(op.f('ix_task_journals_id'), 'task_journals', ['id'], unique=False)
    op.create_index(op.f('ix_user_progress_id'), 'user_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_progress_lesson_id'), 'user_progress', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_progress_lesson_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_id'), table_name='user_progress')
    op.drop_index(op.f('ix_task_journals_id'), table_name='task_journals')
    op.drop_index(op.f('ix_practice_submissions_user_id'), table_name='practice_submissions')
    op.drop_index(op.f('ix_practice_submissions_lesson_id'), table_name='practice_submissions')
    op.drop_index(op.f('ix_practice_submissions_id'), table_name='practice_submissions')
    op.drop_index(op.f('ix_user_course_enrollments_user_id'), table_name='user_course_enrollments')
    op.drop_index(op.f('ix_user_course_enrollments_id'), table_name='user_course_enrollments')
    op.drop_table('user_course_enrollments')
    # ### end Alembic commands ###
