"""Initial migration: add video processing tables

Revision ID: b50a670c4ebd
Revises: 
Create Date: 2026-01-11 12:42:50.056982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b50a670c4ebd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='视频标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='视频描述'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='视频文件路径'),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True, comment='缩略图路径'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='视频时长（秒）'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='文件大小（字节）'),
    sa.Column('format', sa.String(length=50), nullable=True, comment='视频格式'),
    sa.Column('resolution', sa.String(length=20), nullable=True, comment='分辨率，如 1920x1080'),
    sa.Column('status', sa.Enum('UPLOADING', 'PROCESSING', 'COMPLETED', 'FAILED', name='videostatus'), nullable=False, comment='处理状态'),
    sa.Column('difficulty_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel'), nullable=True, comment='难度级别'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='分类'),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True, comment='标签列表'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    op.create_table('processing_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False, comment='视频ID'),
    sa.Column('task_type', sa.Enum('AUDIO_EXTRACTION', 'SUBTITLE_GENERATION', 'TRANSLATION', 'PHONETIC', 'GRAMMAR_ANALYSIS', name='tasktype'), nullable=False, comment='任务类型'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=False, comment='任务状态'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='进度（0-100）'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_tasks_id'), 'processing_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_processing_tasks_video_id'), 'processing_tasks', ['video_id'], unique=False)
    op.create_table('subtitles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False, comment='视频ID'),
    sa.Column('sequence_number', sa.Integer(), nullable=False, comment='字幕序号'),
    sa.Column('start_time', sa.Numeric(precision=10, scale=3), nullable=False, comment='开始时间（秒）'),
    sa.Column('end_time', sa.Numeric(precision=10, scale=3), nullable=False, comment='结束时间（秒）'),
    sa.Column('original_text', sa.Text(), nullable=False, comment='原文（英文）'),
    sa.Column('translation', sa.Text(), nullable=True, comment='翻译（中文）'),
    sa.Column('phonetic', sa.Text(), nullable=True, comment='音标'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtitles_id'), 'subtitles', ['id'], unique=False)
    op.create_index(op.f('ix_subtitles_video_id'), 'subtitles', ['video_id'], unique=False)
    op.create_table('grammar_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subtitle_id', sa.Integer(), nullable=False, comment='字幕ID'),
    sa.Column('sentence_structure', sa.String(length=100), nullable=True, comment='句子结构类型'),
    sa.Column('grammar_points', postgresql.ARRAY(sa.String()), nullable=True, comment='语法点列表'),
    sa.Column('difficult_words', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='难点词汇 [{word, definition, phonetic, part_of_speech}]'),
    sa.Column('phrases', postgresql.ARRAY(sa.String()), nullable=True, comment='常用短语列表'),
    sa.Column('explanation', sa.Text(), nullable=True, comment='整体语法解释'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['subtitle_id'], ['subtitles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_analysis_id'), 'grammar_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_grammar_analysis_subtitle_id'), 'grammar_analysis', ['subtitle_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grammar_analysis_subtitle_id'), table_name='grammar_analysis')
    op.drop_index(op.f('ix_grammar_analysis_id'), table_name='grammar_analysis')
    op.drop_table('grammar_analysis')
    op.drop_index(op.f('ix_subtitles_video_id'), table_name='subtitles')
    op.drop_index(op.f('ix_subtitles_id'), table_name='subtitles')
    op.drop_table('subtitles')
    op.drop_index(op.f('ix_processing_tasks_video_id'), table_name='processing_tasks')
    op.drop_index(op.f('ix_processing_tasks_id'), table_name='processing_tasks')
    op.drop_table('processing_tasks')
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
